services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  mysql:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    ports:
      - 8978:8978
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    depends_on:
      - mysql

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - 5540:5540
    volumes:
      - redisinsight_data:/db
    depends_on:
      - redis

volumes:
  redis_data:
  mysql_data:
  cloudbeaver_data:
  redisinsight_data:
